# Generated by Django 5.2.10 on 2026-02-20 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('category', models.CharField(choices=[('C1', 'CLASS 1'), ('C2', 'CLASS 2'), ('HM', 'HazMat'), ('HH', 'Heavy Haulers'), ('LH', 'Long-Haul'), ('SH', 'Short-Haul')], max_length=20)),
                ('trailer_type', models.CharField(choices=[('DV', 'Dry Van'), ('FRG', 'Refrigerated (Reefer)'), ('FB', 'Flatbed'), ('DD', 'Drop-Deck/Step-Deck'), ('LB', 'Lowboy/Double Drop'), ('TNK', 'Tanker'), ('CON', 'Container')], max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_location', models.CharField(max_length=50)),
                ('available_from', models.DateField()),
                ('description', models.TextField()),
                ('companies', models.ManyToManyField(blank=True, related_name='interested_drivers', to='companies.company')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='drivers.driver')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
