# Generated by Django 5.2.10 on 2026-02-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='drivers',
            field=models.ManyToManyField(blank=True, related_name='interested_offers', to='drivers.driver'),
        ),
    ]
